from django.urls import path

from . import views

urlpatterns = [
    path('sales-tickets/', views.sales_tickets_list, name='sales_tickets'),
    path('edit/<int:ticket_id>/', views.edit_sales_ticket, name='edit_sales_ticket'),
    path('banks/', views.bank_list, name='bank-list'),
    path('orders/edit/<int:order_id>/', views.edit_order, name='edit-order'),
    path('active-orders/', views.active_orders, name='active-orders'),
    path('delete-order/<int:order_id>/', views.delete_order, name='delete-order'),
    path('delete-order-ticket/<int:order_id>/<int:ticket_id>/', views.delete_order_ticket, name='delete-order-ticket'),
    path('active-quotes/', views.active_quotes, name='active-quotes'),
    path('active-invoice/', views.active_invoice, name='active-invoice'),
    path('edit-quote/<int:quote_id>/', views.edit_quote, name='edit-quote'),
    path('delete-quote/<int:quote_id>/', views.delete_quote, name='delete-quote'),
    path('delete-quote-ticket/<int:quote_id>/<int:ticket_id>/', views.delete_quote_ticket, name='delete-quote-ticket'),
    path('convert-to-quote/<int:ticket_id>/', views.convert_to_quote, name='convert-to-quote'),
    path('convert-to-order/<int:ticket_id>/', views.convert_to_order, name='convert-to-order'),
    path('convert-quote-to-order/<int:quote_id>/', views.convert_quote_to_order, name='convert-quote-to-order'),
    path('convert-to-invoice/<int:ticket_id>/', views.convert_to_invoice, name='convert-to-invoice'),
    path('create_ticket/', views.create_ticket, name='create_ticket_sales'),
    path('invoice/<int:invoice_id>/', views.view_invoice, name='view_invoice'),
    path('delete_ticket/<int:ticket_id>/', views.delete_sales_ticket, name='delete_sales_ticket'),
    path('delete_invoice/<int:invoice_id>/', views.delete_sales_invoice, name='delete_sales_invoice'),
    path('delete_invoice/<int:invoice_id>/<int:ticket_id>/', views.delete_sales_invoice_ticket,
         name='delete_sales_invoice_ticket'),
    path('delete_row/<int:product_id>/<int:ticket_id>/', views.delete_row, name='delete_row'),
    path('delete_row_quote/<int:product_id>/<int:quote_id>/', views.delete_row_quote, name='delete_row_quote'),
    path('delete_row_order/<int:product_id>/<int:order_id>/', views.delete_row_order, name='delete_row_order'),
    path('delete_row_invoice/<int:product_id>/<int:invoice_id>/', views.delete_row_invoice, name='delete_row_invoice'),
    path('create_order/', views.create_order, name='create_order'),
    path('quote/<int:quote_id>/', views.quote, name='quote'),
    path('invoice_print/<int:invoice_id>/', views.invoice, name='invoice'),
    path('dashoard2/', views.sales_dashboard, name='sales_dashboard'),
    path('tickets_created_this_year/', views.tickets_created_this_year, name='tickets_created_this_year'),
    path('quotes_created_this_year/', views.quotes_created_this_year, name='quotes_created_this_year'),
    path('orders_created_this_year/', views.orders_created_this_year, name='orders_created_this_year'),
    path('donut_chart_data/', views.donut_chart_data, name='donut_chart_data'),
    path('donut_chart_quotes_data/', views.donut_chart_quotes_data, name='donut_chart_quotes_data'),
    path('donut_chart_orders_data/', views.donut_chart_orders_data, name='donut_chart_orders_data'),
    path('deactivate_order_product/<int:op_id>/<int:order_id>/', views.deactivate_order_product,
         name='deactivate_order_product'),
    path('orders_in_status/<str:status>/', views.orders_in_status, name='orders_in_status'),
    path('tickets_in_status/<str:status>/', views.tickets_in_status, name='tickets_in_status'),
    path('quotes_in_status/<str:status>/', views.quotes_in_status, name='quotes_in_status'),
    path('sales_tickets/<int:ticket_id>/duplicate/', views.duplicate_sales_ticket, name='duplicate_sales_ticket'),
    path('orders/<int:order_id>/duplicate/', views.duplicate_order, name='duplicate_order'),

]
