# Generated by Django 4.2.6 on 2023-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0003_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
