# Generated by Django 4.2.6 on 2023-10-18 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('its', '0004_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='cc_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
