# Generated by Django 4.2.6 on 2023-10-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0008_alter_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
