# Generated by Django 4.2.6 on 2023-11-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0013_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='colour',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
