# Generated by Django 4.2.6 on 2023-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0017_remove_notification_user_notification_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
