# Generated by Django 4.2.6 on 2023-11-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0018_alter_personal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='created_by',
        ),
    ]
