# Generated by Django 4.2.6 on 2024-01-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0022_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='remark',
            field=models.TextField(),
        ),
    ]
