# Generated by Django 4.2.6 on 2023-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoppricelist',
            name='availability',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
