# Generated by Django 4.2.6 on 2023-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_laptoppricelist_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptoppricelist',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
