# Generated by Django 4.2.6 on 2023-11-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_coloursoftpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='rate2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coloursoftpricelist',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
