# Generated by Django 4.2.6 on 2023-11-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_coloursoftpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='rate2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coloursoftpricelist',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FellowesPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, unique=True)),
                ('specs', models.CharField(max_length=255, null=True)),
                ('stock', models.CharField(max_length=255, null=True)),
                ('level_1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('level_2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('level_3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('end_user', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prices.brand')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prices.equipment')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prices.supplier')),
            ],
        ),
    ]
