# Generated by Django 4.2.6 on 2023-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_exchange_rate2_alter_coloursoftpricelist_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptoppricelist',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='laptoppricelist',
            unique_together={('product_name', 'supplier')},
        ),
    ]
