# Generated by Django 4.2.6 on 2023-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_alter_laptoppricelist_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowesPricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(null=True)),
                ('specification', models.TextField(null=True)),
                ('stock', models.CharField(max_length=255, null=True)),
                ('discount', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
