# Generated by Django 4.2.6 on 2023-11-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0013_pricerulemax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_range_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percentage2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.equipment')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricerulemin',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='PriceRuleMax',
        ),
        migrations.DeleteModel(
            name='PriceRuleMin',
        ),
    ]
