# Generated by Django 4.2.6 on 2024-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0016_pricerule_constant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laptoppricelist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='laptoppricelist',
            name='data',
            field=models.IntegerField(null=True),
        ),
    ]
