# Generated by Django 4.2.6 on 2023-11-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technical', '0053_remove_checklistitem_checklist_and_more'),
        ('its', '0012_task_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100)),
                ('mo', models.CharField(max_length=100)),
                ('backup', models.CharField(max_length=100)),
                ('outlook', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('observations', models.TextField()),
                ('recomendation', models.TextField()),
                ('status', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.clients')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.servicetickets')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus', models.CharField(max_length=100)),
                ('psu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('cd_dvd', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=100)),
                ('hdd_status', models.CharField(max_length=100)),
                ('mainboard', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.equipment')),
            ],
        ),
    ]
