# Generated by Django 4.2.6 on 2023-11-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_equipment_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentspecs',
            name='comp_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentspecs',
            name='ip_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='backup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='mo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='outlook',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
