# Generated by Django 4.2.6 on 2023-11-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_equipmentspecs_comp_name_equipmentspecs_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.BooleanField()),
                ('backup', models.BooleanField()),
                ('ports', models.BooleanField()),
                ('battery', models.BooleanField()),
                ('phy_damage', models.BooleanField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.equipment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.BooleanField()),
                ('tone', models.BooleanField()),
                ('phy_damage', models.BooleanField()),
                ('service_interior', models.BooleanField()),
                ('service_roller', models.BooleanField()),
                ('static_eliminator', models.BooleanField()),
                ('fuser_unit', models.BooleanField()),
                ('gears', models.BooleanField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.equipment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy_damage', models.BooleanField()),
                ('colour_display', models.BooleanField()),
                ('vertical_lines', models.BooleanField()),
                ('vga_cable', models.BooleanField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.equipment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
