# Generated by Django 4.2.6 on 2023-11-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_upschecklist_printerchecklist_monitorchecklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='recomendation',
            new_name='recommendation',
        ),
    ]
