# Generated by Django 4.2.6 on 2023-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_recomendation_service_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorchecklist',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printerchecklist',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upschecklist',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
