# Generated by Django 4.2.6 on 2023-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_monitorchecklist_status_printerchecklist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorchecklist',
            name='colour_display',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='monitorchecklist',
            name='phy_damage',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='monitorchecklist',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monitorchecklist',
            name='vertical_lines',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='monitorchecklist',
            name='vga_cable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='fuser_unit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='gears',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='phy_damage',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='power',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='service_interior',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='service_roller',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='static_eliminator',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='printerchecklist',
            name='tone',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='upschecklist',
            name='backup',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='upschecklist',
            name='battery',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='upschecklist',
            name='phy_damage',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='upschecklist',
            name='ports',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='upschecklist',
            name='power',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='upschecklist',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
