# Generated by Django 4.2.6 on 2023-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_monitorchecklist_colour_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='service',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='monitorchecklist',
            name='observations',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitorchecklist',
            name='recommendation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printerchecklist',
            name='observations',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printerchecklist',
            name='recommendation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upschecklist',
            name='observations',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upschecklist',
            name='recommendation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
