# Generated by Django 4.2.6 on 2023-11-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_monitorchecklist_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentspecs',
            name='gen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
