# Generated by Django 4.2.6 on 2023-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_equipmentspecs_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentspecs',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
