# Generated by Django 4.2.6 on 2023-11-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0071_alter_inhousetquote_ticket_and_more'),
        ('service', '0011_equipmentspecs_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('attachment', models.CharField(max_length=1000, null=True)),
                ('currency', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(max_length=255, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.servicetickets')),
            ],
        ),
    ]
