# Generated by Django 4.2.6 on 2023-12-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_servicequote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiv', models.BooleanField(null=True)),
                ('pwr', models.BooleanField(null=True)),
                ('memory', models.BooleanField(null=True)),
                ('fan', models.BooleanField(null=True)),
                ('dvd', models.BooleanField(null=True)),
                ('processor', models.BooleanField(null=True)),
                ('hdd', models.BooleanField(null=True)),
                ('board', models.BooleanField(null=True)),
                ('status', models.TextField(default='Pending')),
                ('observations', models.TextField()),
                ('recommendation', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.equipment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiv', models.BooleanField(null=True)),
                ('pwr', models.BooleanField(null=True)),
                ('memory', models.BooleanField(null=True)),
                ('fan', models.BooleanField(null=True)),
                ('dvd', models.BooleanField(null=True)),
                ('processor', models.BooleanField(null=True)),
                ('hdd', models.BooleanField(null=True)),
                ('board', models.BooleanField(null=True)),
                ('status', models.TextField(default='Pending')),
                ('observations', models.TextField()),
                ('recommendation', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.equipment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='CpuChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiv', models.BooleanField(null=True)),
                ('pwr', models.BooleanField(null=True)),
                ('memory', models.BooleanField(null=True)),
                ('fan', models.BooleanField(null=True)),
                ('dvd', models.BooleanField(null=True)),
                ('processor', models.BooleanField(null=True)),
                ('hdd', models.BooleanField(null=True)),
                ('board', models.BooleanField(null=True)),
                ('status', models.TextField(default='Pending')),
                ('observations', models.TextField()),
                ('recommendation', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.equipment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
