# Generated by Django 4.2.6 on 2023-10-12 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(db_comment='PK', primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=255)),
                ('serial_no', models.CharField(max_length=255)),
                ('eqpass', models.CharField(max_length=255)),
                ('machine_yom', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('rom', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('office_suite', models.CharField(max_length=255)),
                ('printer_yom', models.CharField(max_length=255)),
                ('printer_type', models.CharField(max_length=255)),
                ('catridge', models.CharField(max_length=255)),
                ('fault', models.CharField(max_length=255)),
                ('accessories', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('diagnosis', models.TextField()),
                ('action', models.TextField()),
                ('recommendation', models.TextField()),
                ('labour', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
                ('lpo_no', models.CharField(max_length=255)),
                ('bench_status', models.CharField(max_length=25)),
                ('more', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=25)),
                ('brought_by', models.CharField(max_length=255)),
                ('reg_sign', models.CharField(max_length=255)),
                ('collected_by', models.CharField(max_length=255)),
                ('dlvr_sign', models.CharField(max_length=255)),
                ('tr_approval', models.IntegerField()),
                ('is_active', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('agtsc', models.CharField(max_length=255)),
                ('timeline', models.CharField(max_length=255)),
                ('device_diagnosis', models.CharField(max_length=255)),
                ('sourcing_parts', models.CharField(max_length=255)),
                ('device_repair', models.CharField(max_length=255)),
                ('product_currency', models.CharField(max_length=255)),
                ('device', models.TextField()),
                ('tr_status', models.TextField()),
                ('sourcing_status', models.TextField()),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
