# Generated by Django 4.2.6 on 2023-10-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('availability', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.tickets')),
            ],
        ),
    ]
