# Generated by Django 4.2.6 on 2023-10-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
