# Generated by Django 4.2.6 on 2023-10-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_alter_productdetail_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
