# Generated by Django 4.2.6 on 2023-10-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0005_alter_productdetail_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('lpo', models.CharField(max_length=20, null=True)),
                ('collected_by', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('vat_status', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('department', models.CharField(max_length=50)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technical.tickets')),
            ],
        ),
    ]
