# Generated by Django 4.2.6 on 2023-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0006_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('serial_no', models.CharField(max_length=30, null=True)),
                ('particulars', models.TextField()),
            ],
        ),
    ]
