# Generated by Django 4.2.6 on 2023-10-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0007_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
