# Generated by Django 4.2.6 on 2023-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0009_items_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
