# Generated by Django 4.2.6 on 2023-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0010_alter_delivery_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
