# Generated by Django 4.2.6 on 2023-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0013_alter_delivery_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('req_status', models.CharField(max_length=255)),
                ('issue_status', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('return_status', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'requisitions',
                'managed': False,
            },
        ),
    ]
