# Generated by Django 4.2.6 on 2023-10-17 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0002_clients_company'),
        ('technical', '0014_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCards',
            fields=[
                ('cc_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('equipment', models.CharField(max_length=255)),
                ('fault', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('is_active', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('sign', models.ImageField(upload_to='signatures/')),
            ],
            options={
                'db_table': 'call_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedules',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('notes', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=255)),
                ('is_active', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='its.company')),
            ],
        ),
    ]
