# Generated by Django 4.2.6 on 2023-10-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0015_callcards_serviceschedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedules',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceschedules',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ServiceTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servers', models.IntegerField(null=True)),
                ('cpus', models.IntegerField(null=True)),
                ('laptops', models.IntegerField(null=True)),
                ('printers', models.IntegerField(null=True)),
                ('scanners', models.IntegerField(null=True)),
                ('ups', models.IntegerField(null=True)),
                ('large_ups', models.IntegerField(null=True)),
                ('aios', models.IntegerField(null=True)),
                ('biometrics', models.IntegerField(null=True)),
                ('cctvs', models.IntegerField(null=True)),
                ('highend_machines', models.IntegerField(null=True)),
                ('nas', models.IntegerField(null=True)),
                ('more', models.CharField(max_length=255, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('ticket_id', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, to='technical.serviceschedules')),
            ],
        ),
    ]
