# Generated by Django 4.2.6 on 2023-10-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0017_serviceschedules_techs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='signature',
            new_name='signature_image',
        ),
    ]
