# Generated by Django 4.2.6 on 2023-10-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0010_rename_image_signature_signature_image'),
        ('technical', '0018_rename_signature_delivery_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='delivery',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='its.signature'),
        ),
    ]
