# Generated by Django 4.2.6 on 2023-10-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0020_signaturemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignatureModel',
        ),
    ]
