# Generated by Django 4.2.6 on 2023-10-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0021_delete_signaturemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='signature',
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='technical.delivery')),
            ],
        ),
    ]
