# Generated by Django 4.2.6 on 2023-10-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0023_alter_signature_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='delivery',
            new_name='delivery_id',
        ),
    ]
