# Generated by Django 4.2.6 on 2023-10-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0024_rename_delivery_signature_delivery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='delivery_id',
        ),
    ]
