# Generated by Django 4.2.6 on 2023-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0026_alter_serviceschedules_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=100)),
                ('delivery_id', models.CharField(max_length=100, unique=True)),
                ('signature_image', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
