# Generated by Django 4.2.6 on 2023-10-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0027_deliverys'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='technical.delivery'),
            preserve_default=False,
        ),
    ]
