# Generated by Django 4.2.6 on 2023-10-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0030_delivery_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='created_at',
            new_name='created',
        ),
    ]
