# Generated by Django 4.2.6 on 2023-10-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0034_items_amount_alter_delivery_vat_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('Callcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='technical.callcards')),
            ],
        ),
    ]
