# Generated by Django 4.2.6 on 2023-10-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0035_csignature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csignature',
            old_name='Callcard',
            new_name='callcard',
        ),
    ]
