# Generated by Django 4.2.6 on 2023-10-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0036_rename_callcard_csignature_callcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceschedules',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceschedules',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
