# Generated by Django 4.2.6 on 2023-10-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0037_delivery_updated_alter_serviceschedules_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsourcing',
            name='assignee',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
