# Generated by Django 4.2.6 on 2023-10-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0038_alter_tsourcing_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
