# Generated by Django 4.2.6 on 2023-10-28 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0039_delivery_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsourcing',
            name='attachment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tsourcing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsourcing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tsourcing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='tQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('attachment', models.CharField(max_length=1000, null=True)),
                ('currency', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(max_length=255, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.tickets')),
            ],
        ),
    ]
