# Generated by Django 4.2.6 on 2023-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0042_machinetype_alter_checklist_machine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='company',
        ),
        migrations.AddField(
            model_name='checklist',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
