# Generated by Django 4.2.6 on 2023-10-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0045_equipment_remove_report_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
