# Generated by Django 4.2.6 on 2023-10-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0048_equipment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.servicetickets'),
        ),
    ]
