# Generated by Django 4.2.6 on 2023-10-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0012_task_updated'),
        ('technical', '0049_alter_servicedetails_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='service',
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='its.clients'),
            preserve_default=False,
        ),
    ]
