# Generated by Django 4.2.6 on 2023-10-31 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0050_remove_servicedetails_service_servicedetails_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='client',
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='technical.servicetickets'),
            preserve_default=False,
        ),
    ]
