# Generated by Django 4.2.6 on 2023-10-31 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0051_remove_servicedetails_client_servicedetails_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_info', models.TextField()),
                ('data_info', models.TextField()),
                ('is_signed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='UniqueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('FormatApproval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.formatapproval')),
            ],
        ),
        migrations.CreateModel(
            name='FSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('approved', models.CharField(max_length=255)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.formatapproval')),
            ],
        ),
    ]
