# Generated by Django 4.2.6 on 2023-11-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0052_formatapproval_uniquetoken_fsignature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='checklist_item',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='service',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceDetails',
        ),
    ]
