# Generated by Django 4.2.6 on 2023-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0053_remove_checklistitem_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsourcing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tsourcing',
            name='qty',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
