# Generated by Django 4.2.6 on 2023-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0054_alter_tsourcing_price_alter_tsourcing_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsourcing',
            name='qty',
            field=models.PositiveIntegerField(default=0.0, null=True),
        ),
    ]
