# Generated by Django 4.2.7 on 2023-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0055_alter_tsourcing_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedules',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serviceschedules',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
