# Generated by Django 4.2.6 on 2023-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0058_technicalreport_sent_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalreport',
            name='is_approved',
            field=models.TextField(blank=True),
        ),
    ]
