# Generated by Django 4.2.6 on 2023-11-07 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0059_alter_technicalreport_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
