# Generated by Django 4.2.6 on 2023-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0060_technicalreport_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
