# Generated by Django 4.2.6 on 2023-11-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0062_rename_is_active_technicalreport_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('approved', models.CharField(max_length=255)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.tickets')),
            ],
        ),
    ]
