# Generated by Django 4.2.6 on 2023-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0066_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
