# Generated by Django 4.2.6 on 2023-11-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0070_inhousetickets_inhouseticketimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inhousetickets',
            old_name='lpo_no',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='inhousetickets',
            name='client',
        ),
        migrations.AddField(
            model_name='inhousetickets',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inhousetickets',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
