# Generated by Django 4.2.6 on 2023-11-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0070_inhousetickets_inhousetsourcing_inhousetsignature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhousetquote',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.inhousetickets'),
        ),
        migrations.AlterField(
            model_name='inhousetsourcing',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.inhousetickets'),
        ),
    ]
