# Generated by Django 4.2.6 on 2023-11-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0071_alter_inhousetquote_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsourcing',
            name='assignee',
        ),
    ]
