# Generated by Django 4.2.6 on 2023-11-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0072_remove_tsourcing_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhousetickets',
            name='tr_approval',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tsourcing',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='att/'),
        ),
    ]
