# Generated by Django 4.2.6 on 2023-11-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0074_alter_items_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tquote',
            name='layout',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='inhousetsourcing',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='att/'),
        ),
        migrations.AlterField(
            model_name='serviceschedules',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
