# Generated by Django 4.2.6 on 2024-01-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0075_tquote_layout_alter_inhousetsourcing_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetickets',
            name='aiosdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='biometricsdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='cctvsdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='cpusdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='highend_machinesdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='laptopsdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='large_upsdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='nasdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='printersdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='scannersdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='serversdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetickets',
            name='upsdone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
