# Generated by Django 4.2.6 on 2023-10-19 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('issue_summary', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('via', models.CharField(max_length=255)),
                ('more', models.CharField(max_length=500)),
                ('is_active', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sales_tickets',
                'managed': False,
            },
        ),
    ]
