# Generated by Django 4.2.6 on 2023-10-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_orderproducts_orders_ourbanks_proformainvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoiceProducts',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_no', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('is_active', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'proforma_invoice_products',
                'managed': False,
            },
        ),
    ]
