# Generated by Django 4.2.6 on 2023-10-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_proformainvoiceproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proformainvoiceproducts',
            options={'managed': True},
        ),
    ]
