# Generated by Django 4.2.6 on 2023-10-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_proformainvoiceproducts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proformainvoiceproducts',
            options={'managed': False},
        ),
    ]
